# Generated by Django 5.1.3 on 2024-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cursos/videos/'),
        ),
    ]
