# Generated by Django 5.1.3 on 2024-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_capitulo_video_remove_curso_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
