# Generated by Django 5.1.3 on 2024-11-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_capitulo_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_video', models.FileField(upload_to='videos/')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.capitulo')),
            ],
        ),
    ]
