# Generated by Django 5.1.3 on 2024-11-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_capitulo_contenido_remove_capitulo_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
