# Generated by Django 3.2.20 on 2024-11-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
