# Generated by Django 3.2.20 on 2024-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('last_updated', models.DateField(auto_now=True)),
                ('acceptance', models.TextField()),
                ('content_usage', models.TextField()),
                ('intellectual_property', models.TextField()),
                ('third_party_links', models.TextField()),
                ('modifications', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
    ]
