# Generated by Django 3.2.20 on 2024-11-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0010_termsandconditions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titulo',
            new_name='title',
        ),
    ]
