# Generated by Django 5.1.2 on 2024-11-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0013_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('ubication', models.TextField()),
                ('image_ubication', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
