# Generated by Django 5.1.2 on 2024-11-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0014_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subtitle',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image_ubication',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ubication',
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
