# Generated by Django 5.1.2 on 2024-11-06 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0016_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
