# Generated by Django 5.1.2 on 2024-11-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0018_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
