# Generated by Django 5.1.2 on 2024-11-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0020_blog_product_remove_contact_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
