# Generated by Django 5.1.2 on 2024-11-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0021_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
