# Generated by Django 5.1.2 on 2024-11-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0022_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
