# Generated by Django 5.1.2 on 2024-11-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0023_delete_blog_delete_product_remove_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
