# Generated by Django 5.1.2 on 2024-11-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0024_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
