# Generated by Django 5.1.2 on 2024-11-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0025_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
            ],
        ),
    ]
