# Generated by Django 5.1.2 on 2024-11-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0026_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
