# Generated by Django 5.1.2 on 2024-11-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0027_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
