# Generated by Django 5.1.2 on 2024-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0028_bannerhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_description', models.TextField()),
                ('what_you_can_find', models.JSONField()),
                ('why_we_do_it', models.TextField()),
                ('core_values', models.JSONField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('facebook_url', models.URLField()),
                ('whatsapp_url', models.URLField()),
                ('footer_message', models.TextField()),
            ],
        ),
    ]
