# Generated by Django 5.1.2 on 2024-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0029_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='core_values',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='what_you_can_find',
            field=models.TextField(),
        ),
    ]
