# Generated by Django 5.1.2 on 2024-11-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0030_alter_about_core_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
