# Generated by Django 5.1.2 on 2024-11-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0031_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='team_image',
        ),
    ]
