# Generated by Django 5.1.2 on 2024-11-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0032_rename_image_about_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
