# Generated by Django 5.1.2 on 2024-11-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0033_carousel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='title',
        ),
    ]
