# Generated by Django 5.1.2 on 2024-11-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0035_cursos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='image',
            new_name='cursos_list',
        ),
    ]
