# Generated by Django 5.1.2 on 2024-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0036_rename_image_cursos_cursos_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='cursos_list',
        ),
        migrations.AddField(
            model_name='cursos',
            name='image',
            field=models.ImageField(null=True, upload_to='cursos/'),
        ),
    ]
