# Generated by Django 5.1.2 on 2024-11-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0037_remove_cursos_cursos_list_cursos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='image',
        ),
        migrations.AddField(
            model_name='cursos',
            name='cursos_list',
            field=models.ImageField(null=True, upload_to='cursos_list/'),
        ),
    ]
