# Generated by Django 5.1.2 on 2024-11-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0041_alter_cursos_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
    ]
