# Generated by Django 5.1.3 on 2024-11-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0045_curso_capitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
