# Generated by Django 5.1.3 on 2024-11-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0047_capitulo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='video',
        ),
        migrations.AddField(
            model_name='curso',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='cursos/videos/')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mi_app.capitulo')),
            ],
        ),
    ]
