# Generated by Django 5.1.3 on 2024-11-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0048_remove_capitulo_video_curso_description_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='video',
            name='capitulo',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
