# Generated by Django 5.1.3 on 2024-11-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0051_suscriptores_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
