# Generated by Django 5.1.3 on 2024-12-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0053_delete_calificacion_delete_suscriptores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerhome',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
